config/routes.rb
Rails.application.routes.draw do
  resources :authors
  root 'basic_pages#home'

  get '/search', to: 'search#index'
  get '/about', to: 'basic_pages#about'
  get '/contact', to: 'basic_pages#contact'

  resources :articles
  devise_for :users

  get 'tags/:tag', to: 'articles#index', as: :tag

  mount Ckeditor::Engine => '/ckeditor'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  acts_as_taggable

  belongs_to :author
  mount_uploader :cover_picture, CoverPicUploader
  validates :body, presence: true
  validates :title, presence: true, length: { maximum: 100 }
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :articles

  def to_param
    [id, name.parameterize].join("-")
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :article
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, length: { in: 2..20 }, uniqueness: true

  def to_s
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag]).page(params[:page])
    else
      @articles = Article.page(params[:page])
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    set_author(@article)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :author_id, :cover_picture, :tag_list)
    end

    def set_author(article)
      if article.author_id.nil?
        author = Author.find_or_create_by(name: current_user.username)
        article.author = author
      end
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @articles = @author.articles.order('created_at DESC').page(params[:page])
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :description)
    end
end

app/controllers/basic_pages_controller.rb
class BasicPagesController < ApplicationController
  def home
    @articles = Article.order('created_at DESC').limit('30')
    render layout: false
  end

  def about
  end

  def contact
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @q = Article.search(params[:q])
    @articles = @q.result.page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

app/views/articles/_form.html.slim
section
  = simple_form_for(@article) do |f|
    = f.error_notification 
    .row
      .small-12.columns
        = f.input :title 
    .row
      .small-12.columns
        = f.cktext_area :body, cols: 40, ckeditor: { toolbar: 'mini' } 
    .row
      .small-12.columns
        = f.input :cover_picture, as: :file 
    .row
      .small-12.columns
        = f.association :author
    .row
      .small-12.columns
        = f.label :tag_list, "Tags (separated by commas)"
        = f.text_field :tag_list
    .row
      .small-12.columns
        = f.button :submit, class: 'button success expanded'

app/views/articles/edit.html.erb
<h1 class="text-center">Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.slim
header.text-center
  h1 All Articles
  
.paginate = paginate @articles
.article-list
  - @articles.each do |article|
    .row.columns
      article
        .row
          .medium-6.columns
            h2
              = link_to article.title, article_path(article)
          .medium-3.columns
            .subheader = article.author.name
          .medium-3.columns.text-right
            .subheader = article.created_at.strftime("%B %d, %Y")
        .article-content.text-right
          = truncate(strip_tags(article.body), length: 350)
        p.text-right = link_to "Read Full article", article_path(article), class: "button"
.paginate = paginate @articles

app/views/articles/new.html.erb
<h1 class="text-center">New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.slim
article
  header.text-center
    h1 = @article.title
  .row
    .small-3.columns
      p = link_to @article.author.name, author_path(@article.author)
    .small-3.small-offset-6.columns
      p.text-right = @article.created_at.strftime("%B %d, %Y")
    .small-12.columns
      - if @article.cover_picture.present?
        .cover_pic.text-center
          = image_tag @article.cover_picture_url, alt: @article.cover_picture.filename, width: 500, height: 350
  .row.column
    .body-content
      = raw(@article.body)
  .row.column
    p.tags 
      strong Tags:&nbsp;
      = raw @article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')

app/views/authors/_form.html.slim
= simple_form_for(@author) do |f|
  = f.error_notification

  .row
    .small-12.columns
    = f.input :name
  .row
    .small-12.columns
    = f.input :description

  .row
    .small-12.columns
      = f.button :submit

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.slim
article
  h1 Authors
.row.columns
  = link_to 'New Author', new_author_path, class: 'button success'
.row.columns
  table
    thead
      tr
        th Name
        th Description
        th colspan="3"
    tbody
      - @authors.each do |author|
        tr
          td = author.name
          td = author.description
          td = link_to 'Show', author, class: 'button'
          td = link_to 'Edit', edit_author_path(author), class: 'button'
          td = link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button alert'

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.slim
section
  header
    h1.text-center = @author.name
  .row.columns
    = @author.description
    
  .article-list
    .row.columns
      hr
    - @articles.each do |article|
      .row.columns
        article
          .row
            .medium-6.columns
              h2
                = link_to article.title, article_path(article)
            .medium-3.columns
              .subheader = article.author.name
            .medium-3.columns.text-right
              .subheader = article.created_at.strftime("%B %d, %Y")
          .article-content.text-right
            = truncate(strip_tags(article.body), length: 350)
          p.text-right = link_to "Read Full article", article_path(article), class: "button"
  .paginate = paginate @articles

app/views/basic_pages/about.html.slim
h1 About

app/views/basic_pages/contact.html.slim
h1 Contact

app/views/basic_pages/home.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    title = content_for?(:title) ? yield(:title) : "Aajantrik"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    == render 'layouts/topbar'
    == render 'layouts/flash'
    .orbit aria-label=("Favorite Space Pictures") data-orbit="" role="region" 
      ul.orbit-container
        button.orbit-previous
          span.show-for-sr> Previous Slide
          | ◀︎
        button.orbit-next
          span.show-for-sr> Next Slide
          | ▶︎
        li.is-active.orbit-slide
          img.orbit-image alt="Space" src="https://foundation.zurb.com/sites/docs/assets/img/orbit/01.jpg"
          figcaption.orbit-caption Space, the final frontier.
        li.orbit-slide
          img.orbit-image alt="Space" src="https://foundation.zurb.com/sites/docs/assets/img/orbit/02.jpg" /
          figcaption.orbit-caption Lets Rocket!
        li.orbit-slide
          img.orbit-image alt="Space" src="https://foundation.zurb.com/sites/docs/assets/img/orbit/03.jpg" /
          figcaption.orbit-caption Encapsulating
        li.orbit-slide
          img.orbit-image alt="Space" src="https://foundation.zurb.com/sites/docs/assets/img/orbit/04.jpg" /
          figcaption.orbit-caption Outta This World
      nav.orbit-bullets
        button.is-active data-slide="0" 
          span.show-for-sr First slide details.
          span.show-for-sr Current Slide
        button data-slide="1" 
          span.show-for-sr Second slide details.
        button data-slide="2" 
          span.show-for-sr Third slide details.
        button data-slide="3" 
          span.show-for-sr Fourth slide details.
    #featured
      .row.expanded
        - @articles.each do |article|
          .small-12.medium-6.large-4.columns
            article.home-page
              h2 = article.title
              p.clearfix
                - if article.cover_picture.present?
                  .thumb = image_tag(article.cover_picture_url(:thumb))
                = truncate(strip_tags(article.body), length: 200)
              p.text-justify = link_to "Read More", article_path(article), class: "button"
      .row.expanded
        .small-12.medium-8.columns.medium-offset-2
          = link_to "All articles", articles_path, class: "success expanded button large"
    == render 'layouts/footer'

    coffee:
      $ ->
        $("#navicon").css("display", "none");

app/views/layouts/_flash.html.slim
- flash.each do | name, message |
  - name = "success" if name.eql?('notice')
  = content_tag :div, class: "callout #{name}"  do
    button.close-button aria-label='Close alert' type='button'
      span aria-hidden='true' &times;
    = message

app/views/layouts/_footer.html.slim
.footer-bottom
  p.text-center.copyright &copy; 2016 Sourav Moitra. All rights reserved.
  .row
    .medium-4.columns
      ul
        - if user_signed_in?
          li = link_to "New articles", new_article_path
          li = link_to "Authors", authors_path
        - else
          li = link_to "Admin Login", new_user_session_path
    .medium-4.columns
      ul
        li = link_to "About", about_path
    .medium-4.columns
      ul
        li = link_to "Contact", contact_path

app/views/layouts/_topbar.html.slim
.navbar  
  #widemenu.top-bar
    .top-bar-left
      ul.menu
        li#navicon
          button type="button" class="success button" data-toggle="offCanvasLeft" = icon('navicon')
        li
          a href="/"  Home
        li
          a href="/about" About
        li
          a href="/about" Contact
    .top-bar-right
      form action="/search" method="get"
        ul.menu
          - if user_signed_in?
            li = link_to "New Article", new_article_path
            li = link_to "Authors", authors_path
            li = link_to "Logout", destroy_user_session_path, method: :delete
          li
            input placeholder="Search" type="search" name="q"
          li
            button.button Search

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    title = content_for?(:title) ? yield(:title) : "Aajantrik"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .off-canvas-wrapper
      .off-canvas-wrapper-inner data-off-canvas-wrapper="" 
        /! off-canvas title bar for 'small' screen
        .title-bar data-hide-for="medium" data-responsive-toggle="widemenu" 
          .title-bar-left
            button.menu-icon data-open="offCanvasLeft" type="button" 
            span.title-bar-title Aajantrik
        /! off-canvas left menu
        #offCanvasLeft.off-canvas.position-left data-off-canvas=""
          button.close-button aria-label=("Close menu") data-close="" type="button" 
            span aria-hidden="true"  ×
          ul.vertical.menu
            li
              a href="/"  Home
            li
              a href="/about" About
            li
              a href="/about" Contact
            li
              a href="/articles" Articles
              ul.submenu.menu.vertical
                - Article.order('created_at DESC').limit(30).each do |article|
                  li
                    = link_to article.title, article_path(article)
        /! off-canvas right menu
        == render 'layouts/topbar'
        /! original content goes in this container
        .off-canvas-content data-off-canvas-content="" 
          == render 'layouts/flash'
          == yield
          == render 'layouts/footer'

app/views/search/index.html.slim
header.text-center
  h1 Search Results

.paginate = paginate @articles
.article-list
  - @articles.each do |article|
    .row.columns
      article
        .row
          .medium-6.columns
            h2
              = link_to article.title, article_path(article)
          .medium-3.columns
            .subheader = article.author.name
          .medium-3.columns.text-right
            .subheader = article.created_at.strftime("%B %d, %Y")
        .article-content.text-right
          = truncate(strip_tags(article.body), length: 350)
        p.text-right = link_to "Read Full article", article_path(article), class: "button"
.paginate = paginate @articles